apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod-demo
  labels:
    app: my-nginx-app
    environment: lab
spec:
  containers:
  - name: nginx-container
    image: nginx:1.25-alpine
    ports:
    - containerPort: 80
      name: http
    volumeMounts:
    - name: nginx-html-volume
      mountPath: /usr/share/nginx/html
      readOnly: true
  volumes:
  - name: nginx-html-volume
    configMap:
      name: my-nginx-content-cm
